name: MarSkRebirth
main: com.marquez.marsk.MarSk
version: 1.0.0
depend: [Skript]
commands:
  marsk:
    description: MarSK's default command
  ska:
    description: MarSK addon's area command.